language: objective-c
env:
    - PROJECTNAME=LineSDKStarterObjC
rvm:
    - 2.2.5
before_install:
    - sudo gem install cocoapods -v '1.2.0'
    - cd LineSDKStarterObjC
    - pod update
    - cd ..
osx_image: xcode10
script: "xcodebuild -workspace $PROJECTNAME/$PROJECTNAME.xcworkspace -scheme $PROJECTNAME -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO"
podfile: $PROJECTNAME/Podfile
