# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LineSDKStarterObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LineSDKStarterObjC
  pod 'LineSDK', '~> 4.1.0'
end
